version: '3'

services:
   
  redis-monitoring:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - '8005:8001'
    networks:
      - default

  redis-lodgify:  
    image: redis:latest
    ports:
      - "6666:6379"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  portainer_data:
