version: '3'

services:
   
  redis-monitoring:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - '8005:8001'
    networks:
      - default

  cinema-api:
    image: cinema-api:latest
    restart: unless-stopped
    ports:
      - "8172:80"
      - "8443:443"
    environment:      
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
      - ASPNETCORE_URLS=https://+:443;http://+:80
    networks:
      - default

  movie-aggregator-api:
    image:  movie-aggregator-api:latest
    restart: unless-stopped
    environment:      
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "9172:80"
      - "9443:443"
    networks:
      - default
  
networks:
  default:
    driver: bridge

volumes:
  portainer_data:
