version: '3'

services:
  movies-api:
    image: lodgify/movies-api:3
    ports:
      - "7172:80"
      - "7443:443"
    environment:      
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASS}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PATH}
    networks:
      - default

  # cinema-api:
  #   ports:
  #     - "8174:80"
  #     - "8443:443"
  #   environment:      
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
  #     - ASPNETCORE_URLS=https://+:443;http://+:80
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASS}
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PATH}
  #   networks:
  #     - default

networks:
  default:
    driver: bridge

